version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://myauthuser:securepassword123@db:5432/myauthdb
      - SECRET_KEY=your-super-secret-key-123
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myauthuser
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: myauthdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
